version: "3.8"

services:

  hub:
    container_name: "hub-api"
    build: .
    depends_on:
      - data
    ports:
      - "8081:80"
    volumes:
      - "./hub:/usr/src/hub"
    env_file:
      - "./.env"

  data:
    image: "postgres:alpine"
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: www
      POSTGRES_DB: hub
    ports:
      - "8082:5432"
    expose:
      - 8082