"""Added email model

Revision ID: 00778bc104d0
Revises: c23f18c3e3f5
Create Date: 2020-10-17 04:05:39.455339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00778bc104d0'
down_revision = 'c23f18c3e3f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=1024), nullable=True),
    sa.Column('from_user_id', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('hold_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=3), nullable=True),
    sa.Column('to_all_members', sa.Boolean(), nullable=True),
    sa.Column('to_all_subscribers', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_subscribers',
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('subscriber', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.ForeignKeyConstraint(['subscriber'], ['subscriber.email'], ),
    sa.PrimaryKeyConstraint('email_id', 'subscriber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_subscribers')
    op.drop_table('email')
    # ### end Alembic commands ###
