"""Updated users

Revision ID: 1ae61f78c4f5
Revises: eaee9d5e000d
Create Date: 2020-10-20 15:51:10.723965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae61f78c4f5'
down_revision = 'eaee9d5e000d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('expires_after', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.alter_column('band', 'rate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('band', 'rate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('role')
    # ### end Alembic commands ###
