"""added payments

Revision ID: 213244d95cd2
Revises: f2fa3af2317c
Create Date: 2020-10-22 17:02:28.770739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213244d95cd2'
down_revision = 'f2fa3af2317c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('person_id', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('status', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('person', sa.Column('stripe_payment_id', sa.String(length=255), nullable=True))
    op.add_column('role', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'role', 'payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.drop_column('role', 'payment_id')
    op.drop_column('person', 'stripe_payment_id')
    op.drop_column('person', 'stripe_customer_id')
    op.drop_table('payment')
    # ### end Alembic commands ###
