"""Split emails and tel numbers out from addresses table

Revision ID: 57cd02aceba5
Revises: cecb8cdd183f
Create Date: 2020-11-23 20:15:28.321849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cd02aceba5'
down_revision = 'cecb8cdd183f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_address',
    sa.Column('person_id', sa.String(length=10), nullable=False),
    sa.Column('type_code', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=1024), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('hard_bounce', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'type_code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('email_subscription',
    sa.Column('person_id', sa.String(length=10), nullable=False),
    sa.Column('type_code', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('text_shown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'type_code')
    )
    op.create_table('phone_number',
    sa.Column('person_id', sa.String(length=10), nullable=False),
    sa.Column('type_code', sa.String(length=10), nullable=False),
    sa.Column('number', sa.String(length=13), nullable=True),
    sa.Column('sms', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('person_id', 'type_code'),
    sa.UniqueConstraint('number')
    )
    op.add_column('address', sa.Column('type_code', sa.String(length=10), nullable=False))
    op.drop_column('address', 'marketing')
    op.drop_column('address', 'verified')
    op.drop_column('address', 'type')
    op.drop_column('address', 'usage')
    op.add_column('email', sa.Column('type_code', sa.String(length=3), nullable=False))
    op.drop_column('email', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('type', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_column('email', 'type_code')
    op.add_column('address', sa.Column('usage', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('marketing', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('address', 'type_code')
    op.drop_table('phone_number')
    op.drop_table('email_subscription')
    op.drop_table('email_address')
    # ### end Alembic commands ###
