"""Added created_at

Revision ID: 58cedb07360b
Revises: f87266d7f5a0
Create Date: 2020-10-23 01:25:38.468508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cedb07360b'
down_revision = 'f87266d7f5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'created_at')
    # ### end Alembic commands ###
