"""Added roles and stuff

Revision ID: b0786692c626
Revises: 1ae61f78c4f5
Create Date: 2020-10-21 00:20:39.966666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0786692c626'
down_revision = '1ae61f78c4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('expires_after', sa.Integer(), nullable=True),
    sa.Column('lapse_after', sa.Integer(), nullable=True),
    sa.Column('auto_renews', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.add_column('rate', sa.Column('role_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'rate', 'role_type', ['role_type_id'], ['id'])
    op.add_column('role', sa.Column('ends_on', sa.Date(), nullable=True))
    op.add_column('role', sa.Column('person_id', sa.String(length=10), nullable=False))
    op.add_column('role', sa.Column('role_id', sa.Integer(), nullable=False))
    op.add_column('role', sa.Column('starts_on', sa.Date(), nullable=False))
    op.drop_constraint('role_title_key', 'role', type_='unique')
    op.create_foreign_key(None, 'role', 'person', ['person_id'], ['id'])
    op.drop_column('role', 'id')
    op.drop_column('role', 'expires_after')
    op.drop_column('role', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('expires_after', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_unique_constraint('role_title_key', 'role', ['title'])
    op.drop_column('role', 'starts_on')
    op.drop_column('role', 'role_id')
    op.drop_column('role', 'person_id')
    op.drop_column('role', 'ends_on')
    op.drop_constraint(None, 'rate', type_='foreignkey')
    op.drop_column('rate', 'role_type_id')
    op.drop_table('role_type')
    # ### end Alembic commands ###
