"""Changed password field

Revision ID: cecb8cdd183f
Revises: 0ceb13b7667b
Create Date: 2020-11-19 22:49:45.841919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb8cdd183f'
down_revision = '0ceb13b7667b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('role_type_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('gate_func', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_type.id'], ),
    sa.PrimaryKeyConstraint('role_type_id', 'key')
    )
    op.add_column('person', sa.Column('password_hash', sa.String(length=300), nullable=True))
    op.drop_column('person', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('person', 'password_hash')
    op.drop_table('ability')
    # ### end Alembic commands ###
