"""Smol amend

Revision ID: eaee9d5e000d
Revises: 772925ac8d0f
Create Date: 2020-10-20 00:47:18.623790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaee9d5e000d'
down_revision = '772925ac8d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('band', sa.Column('rate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'band', 'rate', ['rate_id'], ['id'])
    op.alter_column('rate', 'amount',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=False)
    op.alter_column('rate', 'charge',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=False)
    op.alter_column('rate', 'multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               nullable=False)
    op.alter_column('rate', 'starts_on',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rate', 'starts_on',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('rate', 'multiplier',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               nullable=True)
    op.alter_column('rate', 'charge',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=True)
    op.alter_column('rate', 'amount',
               existing_type=sa.NUMERIC(precision=5, scale=3),
               nullable=True)
    op.drop_constraint(None, 'band', type_='foreignkey')
    op.drop_column('band', 'rate_id')
    # ### end Alembic commands ###
