"""updated role

Revision ID: f2fa3af2317c
Revises: 9311eb33528f
Create Date: 2020-10-21 17:06:58.755689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fa3af2317c'
down_revision = '9311eb33528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'role', 'role_type', ['role_id'], ['id'])
    op.drop_column('role_type', 'lapse_after')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_type', sa.Column('lapse_after', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    # ### end Alembic commands ###
