"""Beta completed membership and finance

Revision ID: f87266d7f5a0
Revises: 1d80d402f06a
Create Date: 2020-10-23 01:18:37.831507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87266d7f5a0'
down_revision = '1d80d402f06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('role_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('role_role_id_fkey', 'role', type_='foreignkey')
    op.drop_constraint('role_payment_id_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'role_type', ['role_type_id'], ['id'])
    op.drop_column('role', 'payment_id')
    op.drop_column('role', 'role_id')
    op.add_column('role_type', sa.Column('elected', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_type', 'elected')
    op.add_column('role', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('role', sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_payment_id_fkey', 'role', 'payment', ['payment_id'], ['id'])
    op.create_foreign_key('role_role_id_fkey', 'role', 'role_type', ['role_id'], ['id'])
    op.drop_column('role', 'role_type_id')
    # ### end Alembic commands ###
